services:
  # Backend API Service
  - type: web
    name: wander-ai-api
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: wander-ai-frontend
    env: static
    plan: starter
    buildCommand: npm install && npm run build:client
    staticPublishPath: ./dist/spa
    envVars:
      - key: VITE_API_URL
        value: https://wander-ai-api.onrender.com
    autoDeploy: true
